// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFgDvu88Xq1sHgTfbVVc6tQQJ8U7lecp8',
    appId: '1:406589116800:web:b98c9a9dcb7b47a8403165',
    messagingSenderId: '406589116800',
    projectId: 'pinterest-clone-96fb7',
    authDomain: 'pinterest-clone-96fb7.firebaseapp.com',
    storageBucket: 'pinterest-clone-96fb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOtR1kDNWAMlUqCdvIsJknfhDQXmD18g',
    appId: '1:406589116800:android:895797ca9db5eeda403165',
    messagingSenderId: '406589116800',
    projectId: 'pinterest-clone-96fb7',
    storageBucket: 'pinterest-clone-96fb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtkdfD5eXGTGHTVi5xfS-g06gOh3h-VgI',
    appId: '1:406589116800:ios:297ea019ef4661fc403165',
    messagingSenderId: '406589116800',
    projectId: 'pinterest-clone-96fb7',
    storageBucket: 'pinterest-clone-96fb7.firebasestorage.app',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtkdfD5eXGTGHTVi5xfS-g06gOh3h-VgI',
    appId: '1:406589116800:ios:297ea019ef4661fc403165',
    messagingSenderId: '406589116800',
    projectId: 'pinterest-clone-96fb7',
    storageBucket: 'pinterest-clone-96fb7.firebasestorage.app',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFgDvu88Xq1sHgTfbVVc6tQQJ8U7lecp8',
    appId: '1:406589116800:web:060b2e982d6faa65403165',
    messagingSenderId: '406589116800',
    projectId: 'pinterest-clone-96fb7',
    authDomain: 'pinterest-clone-96fb7.firebaseapp.com',
    storageBucket: 'pinterest-clone-96fb7.firebasestorage.app',
  );
}
